### ISSUE TITLE
No proper error message when a valid r command is used

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#152]
Error in the runner when "rm(list = ls())" is used in the FSK editor. It is a common and frequent command to clean the r environment.

Knime console:

DEBUG ExecuteAction                   Creating execution job for 1 node(s)...
DEBUG NodeContainer                   FSK Runner 0:249 has new state: CONFIGURED_MARKEDFOREXEC
DEBUG NodeContainer                   FSK Runner 0:249 has new state: CONFIGURED_QUEUED
DEBUG NodeContainer                   Listeria model_Final_Final_NEW 0 has new state: EXECUTING
DEBUG NodeContainer                   ROOT  has new state: EXECUTING
DEBUG FSK Runner           0:249      FSK Runner 0:249 doBeforePreExecution
DEBUG FSK Runner           0:249      FSK Runner 0:249 has new state: PREEXECUTE
DEBUG FSK Runner           0:249      FSK Runner 0:249 doBeforeExecution
DEBUG FSK Runner           0:249      FSK Runner 0:249 has new state: EXECUTING
DEBUG FSK Runner           0:249      Adding handler 86a51a36-06dc-48ff-a5c0-8685d9dd5ae5 (FSK Runner 0:249: <no directory>) - 3 in total
DEBUG FSK Runner           0:249      FSK Runner 0:249 Start execute
DEBUG RBinUtil                        External Rscript process error output: 
DEBUG RBinUtil                        External RScript process output: 
DEBUG FSK Runner           0:249      Connected to Rserve in 1 attempts.
DEBUG FSK Runner           0:249      reset
ERROR FSK Runner           0:249      Execute failed: R evaluation failed: "knime.tmp.ret<-NULL;printError<-function(e) message(paste('Error:',conditionMessage(e)));for(exp in tryCatch(parse(text=knime.tmp.script),error=printError)){tryCatch(knime.tmp.ret<-withVisible(eval(exp)),error=printError)
if(!is.null(knime.tmp.ret)) {if(knime.tmp.ret$visible) print(knime.tmp.ret$value)}};rm(knime.tmp.script,exp,printError);knime.tmp.ret$value"
DEBUG FSK Runner           0:249      Execute failed: R evaluation failed: "knime.tmp.ret<-NULL;printError<-function(e) message(paste('Error:',conditionMessage(e)));for(exp in tryCatch(parse(text=knime.tmp.script),error=printError)){tryCatch(knime.tmp.ret<-withVisible(eval(exp)),error=printError)
if(!is.null(knime.tmp.ret)) {if(knime.tmp.ret$visible) print(knime.tmp.ret$value)}};rm(knime.tmp.script,exp,printError);knime.tmp.ret$value"
de.bund.bfr.knime.fsklab.nodes.controller.IRController$RException: R evaluation failed: "knime.tmp.ret<-NULL;printError<-function(e) message(paste('Error:',conditionMessage(e)));for(exp in tryCatch(parse(text=knime.tmp.script),error=printError)){tryCatch(knime.tmp.ret<-withVisible(eval(exp)),error=printError)
if(!is.null(knime.tmp.ret)) {if(knime.tmp.ret$visible) print(knime.tmp.ret$value)}};rm(knime.tmp.script,exp,printError);knime.tmp.ret$value"
	at de.bund.bfr.knime.fsklab.nodes.controller.RController.monitoredEval(RController.java:526)
	at de.bund.bfr.knime.fsklab.nodes.controller.ConsoleLikeRExecutor.executeIgnoreResult(ConsoleLikeRExecutor.java:238)
	at de.bund.bfr.knime.fsklab.nodes.RunnerNodeModel.runSnippet(RunnerNodeModel.java:161)
	at de.bund.bfr.knime.fsklab.nodes.RunnerNodeModel.execute(RunnerNodeModel.java:126)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:567)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1172)
	at org.knime.core.node.Node.execute(Node.java:959)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:561)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: de.bund.bfr.knime.fsklab.nodes.controller.IRController$RException: R evaluation failed: "knime.tmp.ret<-NULL;printError<-function(e) message(paste('Error:',conditionMessage(e)));for(exp in tryCatch(parse(text=knime.tmp.script),error=printError)){tryCatch(knime.tmp.ret<-withVisible(eval(exp)),error=printError)
if(!is.null(knime.tmp.ret)) {if(knime.tmp.ret$visible) print(knime.tmp.ret$value)}};rm(knime.tmp.script,exp,printError);knime.tmp.ret$value"
	at de.bund.bfr.knime.fsklab.nodes.controller.RController.eval(RController.java:515)
	at de.bund.bfr.knime.fsklab.nodes.controller.RController$MonitoredEval.lambda$0(RController.java:1589)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.rosuda.REngine.Rserve.RserveException: voidEval failed, request status: error code: 127
	at org.rosuda.REngine.Rserve.RConnection.voidEval(RConnection.java:182)
	at de.bund.bfr.knime.fsklab.nodes.controller.RController.eval(RController.java:510)
	... 3 more
DEBUG FSK Runner           0:249      FSK Runner 0:249 doBeforePostExecution
DEBUG FSK Runner           0:249      FSK Runner 0:249 has new state: POSTEXECUTE
DEBUG FSK Runner           0:249      FSK Runner 0:249 doAfterExecute - failure
DEBUG FSK Runner           0:249      reset
DEBUG FSK Runner           0:249      clean output ports.
DEBUG FSK Runner           0:249      Removing handler 86a51a36-06dc-48ff-a5c0-8685d9dd5ae5 (FSK Runner 0:249: <no directory>) - 2 remaining
DEBUG FSK Runner           0:249      FSK Runner 0:249 has new state: IDLE
DEBUG FSK Runner           0:249      Configure succeeded. (FSK Runner)
DEBUG FSK Runner           0:249      FSK Runner 0:249 has new state: CONFIGURED
DEBUG FSK Runner           0:249      Listeria model_Final_Final_NEW 0 has new state: IDLE
DEBUG NodeContainer                   ROOT  has new state: IDLE

**Comment by miguelalba** [comment]
Addressed in #169.
